# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - web-app-from-github-actions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://demo1containerregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e754b4f8cfce418f85e0565c4a71c327 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_297db0e07b124c78a2411e5414ca44c1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: demo1containerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e754b4f8cfce418f85e0565c4a71c327 }}/image-demo1project:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'web-app-from-github-actions'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1750ed06828f4e0ea0db6ffff58d64f1 }}
        images: 'demo1containerregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e754b4f8cfce418f85e0565c4a71c327 }}/image-demo1project:${{ github.sha }}'